### ISSUE TITLE
Use `parseHTMLUnsafe` if available

### ISSUE THREAD

**Issue by jaredcwhite** [keithamus/i-html#3]
I know this API is pretty new, but going forward if we want to load Declarative Shadow DOM (DSD) templates contained in the incoming HTML fragments, using this API will guarantee that works, whereas the old `DOMParser` API will not.

What do you think?

**Comment by keithamus** [comment]
Oh yeah that sounds interesting! PRs welcome 😉

**Comment by jaredcwhite** [comment]
I'll see if I can get to it over the weekend…
